### ISSUE TITLE
A number of fixes for init version 1.0.0

### ISSUE THREAD

**Issue by Sergey-Kishkurno** [RostyslavBortman/SolidityBoilerplate#2]
The list below is proposed for consideration:

**Корректировки кода**
Изменить в hardhat.config.ts: строку _import dotenv from 'dotenv'_ на:
_import * as dotenv from 'dotenv'_ — чтобы избежать ошибки: 
hardhat.config.ts:1:8 - error TS1192: Module '".../node_modules/dotenv/types/index"' has no default export.
(Пояснение: “That happens because babel (the one that you were using before) assumes modules.export as default export while typescript (the one that you are using now) does not.”)

**Добавить пакеты и переменные в dependences (package.json):**
_- npm install dotenv
- npm install prettier
- npm install solhint_

**Особые случаи:**
На MacOS пришлось задать переменную:
- _export NODE_OPTIONS=--openssl-legacy-provider_ (аналог в Win?) (чтобы исключить: Error: error:0308010C:digital envelope routines::unsupported - в ответ на запуск: npx hardhat test)

**Comment by RostyslavBortman** [comment]
You can create PR for review and post link here @Sergey-Kishkurno

**Comment by Sergey-Kishkurno** [comment]
@RostyslavBortman Made a PR
